name: Fortify on Demand New

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  FoD-SAST-Scan:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Check out source code
        uses: actions/checkout@v4  # Make sure using v4 explicitly

      - name: Setup Java
        uses: actions/setup-java@v4  # Make sure using v4 explicitly
        with:
          distribution: 'temurin'  # Use OpenJDK distribution
          java-version: '17'       # Specify Java version

      # If you need caching, use v2 explicitly to avoid v4 issues
      - name: Cache Maven dependencies
        uses: actions/cache@v2  # Force use of actions/cache@v2
        with:
          path: ~/.m2/repository  # Cache Maven dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Use hash of pom.xml for cache key
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run FoD SAST Scan
        uses: fortify/github-action@v1  # Keep this version for Fortify
        with:
          sast-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}
          FOD_RELEASE: ${{secrets.FOD_RELEASE_ID}}
          EXTRA_PACKAGE_OPTS: -bt none 
          DO_WAIT: true
          DO_EXPORT: true

      - name: Set up ScanCentral log directory
        run: |
          mkdir -p ${{ github.workspace }}/logs
          echo "ScanCentral logs for the project" > ${{ github.workspace }}/logs/scancentral.log
          zip -r ${{ github.workspace }}/scancentral-package.zip ${{ github.workspace }}/logs

      - name: Upload ScanCentral Logs as Artifact
        uses: actions/upload-artifact@v4  # Upload artifact using v4

      - name: Upload ScanCentral Package as Artifact
        uses: actions/upload-artifact@v4  # Upload artifact using v4
