name: Fortify on Demand New

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  FoD-SAST-Scan:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Check out source code
        uses: actions/checkout@v4  

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Cache Maven dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on the pom.xml file
          restore-keys: |
            ${{ runner.os }}-maven-  # Fallback cache key

      - name: Run FoD SAST Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}
          FOD_RELEASE: ${{secrets.FOD_RELEASE_ID}}
          EXTRA_PACKAGE_OPTS: -bt none 
          DO_WAIT: true
          DO_EXPORT: true

      - name: Set up ScanCentral log directory
        run: |
          mkdir -p ${{ github.workspace }}/logs
          echo "ScanCentral logs for the project" > ${{ github.workspace }}/logs/scancentral.log
          zip -r ${{ github.workspace }}/scancentral-package.zip ${{ github.workspace }}/logs

      - name: Upload ScanCentral Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scancentral-logs
          path: ${{ github.workspace }}/logs/

      - name: Upload ScanCentral Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scancentral-package
          path: ${{ github.workspace }}/scancentral-package.zip
